Tele bot
gitsetgopack/MoneyManager pull request #40
Opened 2024-10-25 05:27 UTC by UmangDiyora

2024-10-25 05:28 UTC, UmangDiyora commented
Telegram Skeleton

2024-10-29 10:27 UTC, UmangDiyora commented
telegram signup and login with telegram collection in Database

2024-10-31 03:33 UTC, abhira0 requested changes

2024-10-31 03:33 UTC, abhira0 commented on Bot/Telegram/tmp.ipynb
> +{
remove this file

2024-10-31 03:33 UTC, abhira0 commented on Bot/Telegram/bot.py
> +import os
run pre-commit on this file, and fix errors.

2024-10-31 03:33 UTC, abhira0 commented on Bot/Telegram/bot.py
> +import os
also, add testcases

2024-10-31 03:39 UTC, merged

2024-10-31 17:01 UTC, abhira0 commented
rename the folder names to lower case!