Resolving test cases, merge issues and system errors
gitsetgopack/MoneyManager pull request #50
Opened 2024-10-31 05:30 UTC by AsthaBhalodiya

2024-10-31 16:57 UTC, abhira0 requested changes

2024-10-31 16:57 UTC, abhira0 commented on create_pyenv.sh
> +#!/bin/bash
remove this file

2024-10-31 16:57 UTC, abhira0 commented on tream release2024.2
> +* [32mab-changes[m
please remove this

2024-10-31 16:57 UTC, abhira0 commented on pytest.ini
> +markers =
why do we need this?

2024-10-31 16:57 UTC, abhira0 commented on api/tests/test_analytics.py
> +# import pytest
uncomment this part

2024-10-31 16:57 UTC, abhira0 commented on README.md
> +
add whats removed

2024-10-31 16:57 UTC, abhira0 commented on Makefile
> +# Define variables
remove all the changes from this file

2024-10-31 18:16 UTC, AsthaBhalodiya commented on pytest.ini
> +markers =
required in some test cases

2024-11-02 00:46 UTC, abhira0 approved these changes

2024-11-02 00:46 UTC, merged